#!/usr/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
OFF='\033[0m'


repo_url=$(git config --get remote.origin.url)

read -p "$(echo -e Veuillez entrer un ${MAGENTA}message de commit${OFF} :  )" commit

git add . > /dev/null 2>&1

echo -e "Listes des ${CYAN}fichiers modifiés${OFF} :"
git diff --cached --name-only > .pushedfile

while IFS= read -r line; do
    echo "📄 $line"
done < .pushedfile

rm .pushedfile


read -p "Confirmation? (y/n) : " confirm_push
if [[ "$confirm_push" != "y" && "$confirm_push" != "Y" ]]; then
    echo "❌ Push annulé par l'utilisateur."
    exit 0
fi

echo "📝 Création du commit avec le message : '$commit'"
git commit -m "$commit" > /dev/null 2>&1

echo "🚀 Envoi des modifications vers le dépôt distant..."
git push > /dev/null 2>&1

if [ -n "$repo_url" ]; then
    if [[ "$repo_url" == git@* ]]; then
        repo_url=$(echo "$repo_url" | sed -E 's|git@(.*):|https://\1/|' | sed 's|\.git$||')
    fi

    echo "🌐 Ouverture du dépôt dans le navigateur : $repo_url"
    xdg-open "$repo_url" > /dev/null 2>&1
else
    echo "❌ Impossible de récupérer l'URL du dépôt distant."
fi

echo "✅ Opération terminée avec succès !"