#!/usr/bin/bash
#
###############################################################################
##
## YOU NEED TO MODIFY THIS FILE TO CONTINUE
## FOLLOW THE FOLLOWING STEPS TO BE ABLE TO USE THIS SCRIPTS
## 
## Use this file to call the coding style script
## You need to implement the following lines
##
## python3 <Path_To_This_Repo>/Mouli/main.py
## python3 <Path_To_This_Repo>/Mouli/display_data
##
###############################################################################